replicaCount: 1

image:
  repository: nahuels/svitla-test
  pullPolicy: IfNotPresent
  tag: "latest"
  namespace: svitla

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  className: rf-nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: svitla.local
      paths:
        - path: /
          pathType: Prefix



resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "250m"

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: "rf-storage-rw"
